spring:
  cloud:
    gateway:
#      globalcors: #跨越
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#            allowCredentials: true  # cookie：身份识别，允许携带cookie跨域

      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用服务名进行路由
          enabled: true
      routes:
        - id: service-ticket
          uri: lb://service-ticket
          predicates:
            - Path=/*/ticket-service/**  # 匹配请求路径
logging:
  level:
    root: info


